version: '3'

services:
    app-shell:
        build: ./app-shell
        environment:
            - PORT=3000
        ports:
            - "3000:3000"
    app-wc:
        build: ./fragments/app-wc
        environment:
            - PORT=3001
        ports:
            - "3001:3001"
    app-react:
        build: ./fragments/app-react
        environment:
            - PORT=3002
        ports:
            - "3002:3002"
    app-vue:
        build: ./fragments/app-vue
        environment:
            - PORT=3003
        ports:
            - "3003:3003"
    app-ng:
        build: ./fragments/app-ng
        environment:
            - PORT=3004
        ports:
            - "3004:3004"
